- name: refresh cache
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:clear --no-warmup {{ symfony_cache_options }}"
- name: warm-up cache again
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:warmup {{ symfony_cache_options }}"
- name: fix symfony cache directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}/var/cache"
    recurse: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
- name: fix symfony web directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}/public"
    recurse: yes
    follow: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
